Acho que agora foi o pull request certo
menotti/ld pull request #19
Opened 2022-03-15 15:03 UTC by felipecasarin

2022-03-15 15:03 UTC, felipecasarin commented
Foi?

2022-03-15 18:36 UTC, menotti requested changes
Favor providenciar as mudanças solicitadas

2022-03-15 18:36 UTC, menotti commented on hdlbits/043_bcdadd100/README.md
> +O programa soma 100 dígitos BCD utilizando vetores de 400 bits. Para isso, a variável genvar é utilizada no loop generate-for para iterar valores de 4 em 4 ea varrer os dígitos, armazenando o valor n
A explicação precisa melhorar um pouco:
- `genvar` não é a variável, mas o tipo, a variável é `i`;
- Corrigir *ae*; 
- `cout_wire` não recebe a soma (`sum` recebem), mas transfere os _vai um_ de um dígito para outro.

2022-03-15 18:36 UTC, menotti commented on hdlbits/README.md
> +- [Adder de BCD de 100 dígitos](043_bcdadd100)
Acho que `Somador BCD de 100 dígitos` ficaria melhor

2022-03-15 18:59 UTC, felipecasarin commented
Acho que consegui agora

2022-03-15 19:03 UTC, menotti requested changes

2022-03-15 19:03 UTC, menotti commented on hdlbits/043_bcdadd100/043_bcdadd100.sv
> +module top_module(
Só falta renomear este arquivo, removendo o número do início. Desculpe, não notei antes.

2022-03-15 19:03 UTC, menotti commented on hdlbits/043_bcdadd100/README.md
> +# Explicação
Aproveite e use a **formatação** do `Markdown` para _destacar_ nomes das variáveis. ;-)

2022-03-15 19:03 UTC, menotti commented on hdlbits/043_bcdadd100/043_bcdadd100.sv
> +module top_module(
Use o comando `git mv`

2022-03-15 19:10 UTC, felipecasarin commented
Foi?

2022-03-15 19:19 UTC, menotti commented on hdlbits/043_bcdadd100/README.md
> +# Explicação
Por favor, use ` no lugar de \

2022-03-15 19:21 UTC, menotti requested changes
Por favor, use ` no lugar de \

2022-03-15 20:06 UTC, merged

2022-03-15 20:07 UTC, menotti commented
Ótimo!

2022-10-11 07:06 UTC, felipecasarin commented
Como faço para realizar essas alterações sem ter que fazer o pull request
novamente?

Em ter., 15 de mar. de 2022 às 15:36, Ricardo Menotti <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
>
> Favor providenciar as mudanças solicitadas
> ------------------------------
>
> In hdlbits/043_bcdadd100/README.md
> <https://github.com/menotti/ld/pull/19#discussion_r827298066>:
>
> > @@ -0,0 +1,3 @@
>
> +# Explicação
>
> +
>
> +O programa soma 100 dígitos BCD utilizando vetores de 400 bits. Para isso, a variável genvar é utilizada no loop generate-for para iterar valores de 4 em 4 ea varrer os dígitos, armazenando o valor na variável cout_wires, de tamanho 100.
>
>
> A explicação precisa melhorar um pouco:
>
>    - genvar não é a variável, mas o tipo, a variável é i;
>    - Corrigir *ae*;
>    - cout_wire não recebe a soma (sum recebem), mas transfere os *vai um*
>    de um dígito para outro.
>
> ------------------------------
>
> In hdlbits/README.md
> <https://github.com/menotti/ld/pull/19#discussion_r827298747>:
>
> > @@ -41,6 +41,7 @@ Se você não lê bem em inglês, pode abrir uma segunda janela do site [usando
>
>  - [Evitando _latches_](036_always_nolatches)
>
>  - [Inversão de vetor com `for`](040_vector100r)
>
>  - [Contagem de bits 1](041_popcount255)
>
> +- [Adder de BCD de 100 dígitos](043_bcdadd100)
>
>
> Acho que Somador BCD de 100 dígitos ficaria melhor
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/menotti/ld/pull/19#pullrequestreview-910662541>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYGG6NWLPXSPLQKAC3GKMS3VADKERANCNFSM5QY63EDA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-12 02:08 UTC, menotti commented
Oi Felipe, tudo bem?
Não entendi sua pergunta, já que o _pull resquest_ foi _merged_ lá em 15 de Março